osx_image: xcode7.3
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage update --platform iOS,Mac

script:
- xcodebuild clean build -project Malibu.xcodeproj -scheme Malibu-iOS -sdk iphonesimulator
- xcodebuild test -project Malibu.xcodeproj -scheme Malibu-iOS -sdk iphonesimulator
- xcodebuild clean build -project Malibu.xcodeproj -scheme Malibu-Mac -sdk macosx
- xcodebuild test -project Malibu.xcodeproj -scheme Malibu-Mac -sdk macosx
